# Generated by Django 3.1.7 on 2022-07-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_finreq_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finreq',
            old_name='aadharcard',
            new_name='passport',
        ),
        migrations.RemoveField(
            model_name='finreq',
            name='pancard',
        ),
    ]
